### ISSUE TITLE
Using the model, Complete Training and Optimize Hyperparameters

### ISSUE THREAD

**Issue by LobnaFEZEI** [JRC1995/Abstractive-Summarization#13]
First, I want to thank you for your work.
Reading the future work to be done I got a lil bit confused: Complete Training and Optimize Hyperparameters    isn't training already done? am seeing that U have already used the validation dataset but as a training dataset. Can U tell a lil bit more about the last part of the code "Training and Validation". 

I want to try the model on a new article, however am new to tensorflow. I didn't get how to use the model generated on a new input. I used a usual command line model.predict (the one used for sklearn for example) but didn't get a result. Can U lead me to the right command to use to model files generated?

**Comment by JRC1995** [comment]
>  isn't training already done?

Kind of....I guess you could run for more epochs (I don't think I ran till convergence) with more data. 

> am seeing that U have already used the validation dataset but as a training dataset. Can U tell a lil bit more about the last part of the code "Training and Validation".

Validation is not done by training dataset. Validation is being done on a separate validation dataset after going through an iteration over all training data. (may be better to add validation after every 1000 steps or something)

This section is for training

`            cost,prediction,\
                acc, _ = sess.run([cross_entropy,
                                   outputs,
                                   accuracy,
                                   train_op],
                                  feed_dict={tf_text: train_batches_text[j],
                                             tf_embd: embd,
                                             tf_summary: train_batches_summary[j],
                                             tf_true_summary_len: train_batches_true_summary_len[j],
                                             tf_train: True})
            `

This section is for validation with separate validation data (val_batches_summary)
`
            cost, prediction,\
                acc = sess.run([cross_entropy,
                                outputs,
                                accuracy],
                                  feed_dict={tf_text: val_batches_text[i],
                                             tf_embd: embd,
                                             tf_summary: val_batches_summary[i],
                                             tf_true_summary_len: val_batches_true_summary_len[i],
                                             tf_train: False})`

**Comment by JRC1995** [comment]
> Can U tell a lil bit more about the last part of the code "Training and Validation".

What do you want to know in particular?


>  I didn't get how to use the model generated on a new input. 

Keep the model descriptions - (the tensorflow functions and everything) the same,



Then change the training validation (or make a new cell for prediction with these):


use 

`        train_saver.restore(sess, 'Model_Backup/Seq2seq_summarization.ckpt')
        sess.run(tf.global_variables())
        sess.run(tf.tables_initializer())
`

to restore saved variables (after they are saved). 

and then instead of training/vallidation run something like:


prediction = sess.run(outputs, feed_dict={tf_text: your_text, tf_embd: embd, tf_train: False})


in your_text you put your own personal data with But the data must be reshaped to [batch_size, sequence_size] format, if it's just one data use batch_size as 1, and the data must be vectorized 

use something like your_text = [vocab2idx.get(word,vocab2idx['<UNK>']) for word in your_text]
Then reshape to [1, sequence_size].

**Comment by LobnaFEZEI** [comment]
Thank you so much for ur reactivity and detailed answer.
> What do you want to know in particular.
>"cost, prediction,\ acc = sess.run([cross_entropy, outputs, accuracy], feed_dict={tf_text: val_batches_text[i], tf_embd: embd, tf_summary: val_batches_summary[i], tf_true_summary_len: val_batches_true_summary_len[i], tf_train: False})" 


is used for validation but isn't validation supposed to be using the model generated by the training? in which part of this command line is it calling the trained model?

Do you have any idea why it's showing this error " 'train_saver' is not defined" each time I wanna use "time_saver"? (even answering [y] to ur code is showing this error).

Thank you a lot for your detailed answer about using the model, I have tried a lot before asking, I'll try out your solution and get back to you.

**Comment by JRC1995** [comment]
> is used for validation but isn't validation supposed to be using the model generated by the training? 

validation is used for model selection. we check validation performance periodically while training (we don't train on validation, only check) to decide when to checkpoint, when to save, when to stop training etc. 

Test set is finally used in the end. I didn't implement testing. But one should. 

> in which part of this command line is it calling the trained model?

```
       saver.restore(sess, 'Model_Backup/Seq2seq_summarization.ckpt')
        sess.run(tf.global_variables())
        sess.run(tf.tables_initializer())
```

This part does restores the trained model from checkpoint. 

```
            cost,prediction,\
                acc, _ = sess.run([cross_entropy,
                                   outputs,
                                   accuracy,
                                   train_op],
                                  feed_dict={tf_text: train_batches_text[j],
                                             tf_embd: embd,
                                             tf_summary: train_batches_summary[j],
                                             tf_true_summary_len: train_batches_true_summary_len[j],
                                             tf_train: True})
```
            
This part does the training.



> Do you have any idea why it's showing this error " 'train_saver' is not defined" each time I wanna use "time_saver"? (even answering [y] to ur code is showing this error).

Sorry; typo. It should be "saver" not "train_saver", since I used "saver = tf.train.Saver()".
I didn't notice the error because I think I never tried to restore saved points with y.  I will update the repo.

**Comment by JRC1995** [comment]
> in which part of this command line is it calling the trained model

For a bit more details:

This part initializes the tensorflow variables if you are not restoring any pre-saved variables.

```
        init = tf.global_variables_initializer()
        sess.run(init)
        sess.run(tf.tables_initializer())
```

Otherwise this part restores pre-saved variables when answering "y":

```
       saver.restore(sess, 'Model_Backup/Seq2seq_summarization.ckpt')
        sess.run(tf.global_variables())
        sess.run(tf.tables_initializer())
```

After this the code will load the model with its variables in the memory. You don't need to call the trained models explicitly anymore, because the model graph and its variables should be already loaded. The previous cells with the tf functions and variables should generate the tf graph, 

"with tf.Session() as sess:" should start a tf session with the specific tf model graph and the above codes should initialize/restrore the trainable tf variables. 

```
            cost, prediction,\
                acc = sess.run([cross_entropy,
                                outputs,
                                accuracy],
                                  feed_dict={tf_text: val_batches_text[i],
                                             tf_embd: embd,
                                             tf_summary: val_batches_summary[i],
                                             tf_true_summary_len: val_batches_true_summary_len[i],
                                             tf_train: False})
```

What this part does is compute the specified tensorflow terms (cross_entropy, outputs, accuracy) under the current session. cross_entropy, outputs, accuracy refers to pre-defined terms from previous cells. To compute does terms, tensorflow library automatically runs any other model components that are necessary to compute them. For example, cross_entropy at least requires you to compute this first:

```
tf.nn.sparse_softmax_cross_entropy_with_logits(
        labels=tf_summary, logits=decoder_outputs)
```

for this you need tf_summary data, and the decoder_outputs. But for the decoder outputs you have to essentially run the whole model. Tensorflow library will automatically take care of that and run the necessary components. Same for computing 'accuracy', and 'outputs'. 

Note that when using validation (same for testing and predicting) as in this case, we are not using 'train_op' in sess.run. Computing 'train_op' includes computing gradients and running the optimizer -essentially doing backpropagation based updates (in other words, training). So if you include 'train_op' or not determines whether you are training the model, or just checking it. 

Other than that, to compute cross_entropy, outputs, and such you also need to feed necessary data to the model. tf_summary, tf_text, tf_embd are placeholders - i.e they 'hold' the 'place' for certain datastructures based on which the model graph is created. During training, testing, validation or prediction you have to 'fill' in the places held by placeholders to actually make the model work. 

So cross_entropy requires tf_summary data (so you need to feed it). Cross_entropy also requires decoder_outputs which in turn requres tf_text (the input data) so you have to feed data to tf_text too. Similarly other placeholders are need to be fed with necessary data. This is the explanation behind this part:

```
                                  feed_dict={tf_text: val_batches_text[i],
                                             tf_embd: embd,
                                             tf_summary: val_batches_summary[i],
                                             tf_true_summary_len: val_batches_true_summary_len[i],
                                             tf_train: False})
```

Since we are doing validation in this part, we are explicitly feeding validation data (example 'val_batches_text' instead of 'train_batches_text') - data on which we never trained (never used 'train_op' under sess.run) 

When making a prediction  (predicting a new summary) without having any label data (labeled summary), you don't have the tf_summary data or the tf_true_summary_len data. You won't be able to compute accuracy or cross entropy either. In that case, you will be only computing the outputs of the model based on tf_text. tf_embd, and tf_train will be necessary to feed with data as well though.

**Comment by LobnaFEZEI** [comment]
Didn't want to get back to you until searching more. 
But even after trying to find the answer my own, still the part of reshaping is not clear.
Am always trying to predict one summary using the model generated. 

So after using this code and generating a vector from my text 
S=[vocab2idx.get(word,vocab2idx['<UNK>']) for word in tokinput]

And this to reshape SA=tf.reshape(S,[1,len(S)])
where S is a list of int (the comment to summarize) 

I used this code for prediction:
prediction = sess.run(outputs, feed_dict={tf_text: SA, tf_embd: embd, tf_train: False})

I have received this error:
TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles. For reference, the tensor object was Tensor("Reshape_148:0", shape=(1, 23), dtype=int32) which was passed to the feed with key Tensor("Placeholder:0", shape=(?, ?), dtype=int32).

I have tried different formats of text but still the same error. 
Can you tell me more about reshaping or do you have any idea why am still getting this error. 
Thanks again!

**Comment by JRC1995** [comment]
Intuitively, you can think of the Training and Validation portion as 'outside Tensorflow' in a sense, where you merely run tensorflow graph component through tensorflow sess.run, or save parameters with tf.train.saver but everything else is normal python. 

So in this case, the reshaping should be through something like numpy (np.reshape) instead of tf. 

What is happening here is that we are reshaping our original data in some multi-array format (could be numpy, or perhaps in a form of a nested list) and then feeding it to the 'tf_xyz' placeholders - essentially we fill the 'held place' by the tf placeholders (like tf_text) with numpy/multi-array data having the same shape structure as defined for the placeholder.

As an example, take note of the  train_batches_text[j] and such, they are not tensor objects but numpy multi-arrays (as you can see in the pre-processing scripts). 

You can 'import numpy as np' and then do np.reshape - which should solve the immediate issue. 

also this code should be:

`S=[vocab2idx.get(word,vocab2idx['<UNK>']) for word in tokinput]`

 Sorry for missing the unk part earlier.

**Comment by JRC1995** [comment]
A simple way to do what you want, for testing a single text without any numpy and reshaping is to simply feed '[S]' ( 'tf_text: [S]' ) ([S] would be automatically interpreted as 1 x len(S) shape because of it's a nested-list of that shape)

**Comment by LobnaFEZEI** [comment]
Thank you so much! That helped (the simple way you suggested didn't work, I guess reshaping is always needed). However, using simply numpy is working perfectly. Thanks a lot for all your detailed answers!
