### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint:

### ISSUE THREAD

**Issue by Niko55** [JRC1995/Abstractive-Summarization#15]
I'm trying to run this with Google Colab (GPU setting), with Tensorflow 2.0 
It shows following error
saver.restore(sess, "/content/drive/My Drive/Colab Notebooks/Data/release/Model_Backup/Seq2seq_summarization.ckpt")

Following is the Code:
`
with tf.Session() as sess:  # Start Tensorflow Session
    display_step = 100
    patience = 5

    load = input("\nLoad checkpoint? y/n: ")
    print("")
    saver = tf.train.Saver(tf.global_variables(), )

    if load.lower() == 'y':

        print('Loading pre-trained weights for the model...')
        saver.restore(sess, "/content/drive/My Drive/Colab Notebooks/Data/release/Model_Backup/Seq2seq_summarization.ckpt")
        sess.run(tf.global_variables())
        sess.run(tf.tables_initializer())
`

**Comment by JRC1995** [comment]
You have trained without loading checkpoint and made sure that a checkpoint is created, right?
Because, I haven't provided any checkpoint in github, and you cannot load checkpoint by entering 'y' until there is a checkpoint.
If you already have a checkpoint I am not sure why the error is there. I am not too familiar with either Tensorflow 2.0 or Google Colab. This could be:

A directory path issue related to Colab or something else. Perhaps the whitespace in the directory doesn't work. Perhaps try this: 
`path = r"C:\Users\mememe\Google Drive\Programs\Python\file.csv"`
https://stackoverflow.com/questions/14852140/whitespaces-in-the-path-of-windows-filepath#25650185

Other than that, it could be due to using Tensorflow 2.0 (the code is from 1.12). I guess you have to use tensoflow.compat.v1 or something like that everywhere - even then something may be causing issues due to version differences.

**Comment by Niko55** [comment]
Thanks a lot, it worked. Keep up the good work!
